### ISSUE TITLE
graph和hbs数据insert后没commit的问题

### ISSUE THREAD

**Issue by BenJLocke** [open-falcon/falcon-plus#148]
我在测试的时候发现endpoint和host表的数据一直没有插入。经过测试，发现graph和hbs进行数据插入后没有进行commit操作。
我现在的解决方法是把数据库的autocommit设置为1，用自动commit的方法解决。 

这个是我的配置问题或者是环境问题？

**Comment by hdksky** [comment]
数据库的默认autocommit配置就是1
你先看看自己的环境配置

**Comment by BenJLocke** [comment]
你的意思是，就是依赖MySQL数据库的autocommit =1？ 如果设置为autocommit =0就不行了？ 这样不大好吧？

**Comment by chachacha88** [comment]
1.dashboard配置
# portal database
# TODO: read from api instead of db
PORTAL_DB_HOST = os.environ.get("PORTAL_DB_HOST","127.0.0.1")
PORTAL_DB_PORT = int(os.environ.get("PORTAL_DB_PORT",3306))
PORTAL_DB_USER = os.environ.get("PORTAL_DB_USER","root")
PORTAL_DB_PASS = os.environ.get("PORTAL_DB_PASS","password")
PORTAL_DB_NAME = os.environ.get("PORTAL_DB_NAME","falcon_portal")

# alarm database
# TODO: read from api instead of db
ALARM_DB_HOST = os.environ.get("ALARM_DB_HOST","127.0.0.1")
ALARM_DB_PORT = int(os.environ.get("ALARM_DB_PORT",3306))
ALARM_DB_USER = os.environ.get("ALARM_DB_USER","root")
ALARM_DB_PASS = os.environ.get("ALARM_DB_PASS","password")
ALARM_DB_NAME = os.environ.get("ALARM_DB_NAME","alarms")

2.transfer
    "judge": {
        "enabled": true,
        "batch": 200,
        "connTimeout": 1000,
        "callTimeout": 5000,
        "maxConns": 32,
        "maxIdle": 32,
        "replicas": 500,
        "cluster": {
            "judge-00" : "127.0.0.1:6081"
        }
    },
    "graph": {
        "enabled": true,
        "batch": 200,
        "connTimeout": 1000,
        "callTimeout": 5000,
        "maxConns": 32,
        "maxIdle": 32,
        "replicas": 500,
        "cluster": {
            "graph-00" : "127.0.0.1:6070"
        }
    }

3. agent
"heartbeat": {
        "enabled": true,
        "addr": "127.0.0.1:6030",
        "interval": 60,
        "timeout": 1000
    },
    "transfer": {
        "enabled": true,
        "addrs": [
            "127.0.0.1:8433"
        ],
        "interval": 60,
        "timeout": 1000
    }

4.配置策略
1>.net.port.listen/port=9999
2>.all(#3)<1
3>.告警接收组: falcon

问题描述：端口的监听状况可以接收到，但警告模块一致没有数据

**Comment by hdksky** [comment]
@BenJLocke ，mysql默认就是autocommit=1，如果你手动关闭这个配置，大部分使用innodb的程序都会工作异常。
当然也可以通过在程序里面强化提交逻辑（有些JDBC会帮忙做这个事），但是会导致client和mysql server的交互增加2倍，在网络环境不好或者是并发度非常高的场景下，会严重影响程序的性能。
所以一般情况下，就使用mysql的默认配置就好。

**Comment by hdksky** [comment]
@chachacha88 ，你这个问题最好新开一个issus来描述

**Comment by BenJLocke** [comment]
感觉你们在数据库操作中没有事务的概念。

**Comment by hdksky** [comment]
关于MySQL和Innodb的特性与性能不在这里讨论，具体特性和使用场景，你可以去了解下官方文档,https://dev.mysql.com/doc/    @BenJLocke
