### ISSUE TITLE
Add arm64 support

### ISSUE THREAD

**Issue by odidev** [open-falcon/falcon-plus#901]
Hi,

I am checking on adding arm64 jobs in travis.

I was trying to build the docker image for arm64 but it was failing with below error
```
standard_init_linux.go:211: exec user process caused "exec format error"
```
This package uses openfalcon/makegcc-golang:1.10-alpine as base image for building docker images which are not available for arm64. I am unable to find this image and its Dockerfile to add support for arm64.

Travis Link for arm64 : https://travis-ci.com/github/odidev/falcon-plus/jobs/382607644

I want to know whether you are planning on adding arm64 support and can I get any suggestions on adding arm64 support to Dockerfile and uploading it to docker hub?

**Comment by laiwei** [comment]
open-falcon is not fully tested in arm platform now. @odidev

**Comment by odidev** [comment]
Hi,

I am happy to help in providing the arm64 support in this. But I am unable to get the source of openfalcon/makegcc-golang:1.10-alpine docker image to add arm64 support. It will be helpful if I can get any suggestions on this.

**Comment by JimmyTinsley** [comment]
> 
> 
> Hi,
> 
> I am happy to help in providing the arm64 support in this. But I am unable to get the source of openfalcon/makegcc-golang:1.10-alpine docker image to add arm64 support. It will be helpful if I can get any suggestions on this.

Hello @odidev , 

I'm also intersted in running open-falcon on arm platform.
You mentioned that you didn't get the source of openfalcon/makegcc-golang:1.10-alpine docker image. Actually I found the following codes in [this image's docker hub README](https://hub.docker.com/r/openfalcon/makegcc-golang) and successfully built  it on my arm64 machine. 
```Dockerfile
FROM golang:1.10-alpine3.7 
LABEL maintainer laiwei
RUN apk add --no-cache gcc musl-dev make
```
You could create a Dockerfile with these codes to build your own arm version of makegcc-golang:1.10-alpine docker image, or use the one I just created https://hub.docker.com/r/jimmytinsley/makegcc-golang. 
Just edit `falcon-plus/Dockerfile`, use this or you own makegcc-golang docker image tag
```Dockerfile
FROM jimmytinsley/makegcc-golang
```
instead of 
```Dockerfile
FROM openfalcon/makegcc-golang:1.10-alpine
```
and it should work fine. 

All falcon-plus backend services and dashboard frontend service ran successfully on my arm machine. I didn't test everything but for basic functionalities like collecting and graphing data points, they all work pretty well. I believe it worths trying.
Hope these help.

**Comment by odidev** [comment]
Thanks for the reply and jimmytinsley/makegcc-golang image. I have used this image and was able to resolve this issue and have moved ahead with the build but I am facing some other [issues ](https://drive.google.com/file/d/1khmRN_NBlFyeGJAq8DaAmI2soU8U2dCd/view?usp=sharing)while testing it with **./docker_test.sh.**
```
graph: ERROR (spawn error)
hbs: ERROR (spawn error)
judge: started
transfer: started
nodata: ERROR (spawn error)
aggregator: ERROR (spawn error)
agent: started
gateway: started
api: ERROR (spawn error)
alarm: ERROR (spawn error)
time="2020-10-30T13:08:06Z" level=fatal msg="db conn failed with error connect to 
falcon_portal: Error 1130: Host '172.17.0.1' is not allowed to connect to this MySQL server"
FAIL    github.com/open-falcon/falcon-plus/modules/api/test     0.019s
FAIL
make: *** [Makefile:100: test] Error 1

```
I am currently checking it but if you have come across the above issue and have any resolution please suggest.

**Comment by odidev** [comment]
I was trying to build this package from source for the arm64 platform by using these [steps ](https://drive.google.com/file/d/14gav338ZsAN5KXILapfVynLzqSA-L4Ec/view?usp=sharing)and have tested via make test command.
The package is successfully built for arm64(xenial).
I was also trying to build this package over travis for arm64 with following [changes ](https://github.com/odidev/falcon-plus/commit/0b558b1b430a586129144e6caaf933389554d974)but it is failing for arm64 as this package uses mysql:5.7 docker image which is not available for arm64. I have tried building this package with [mysql/mysql-server:8.0](https://hub.docker.com/r/mysql/mysql-server/) image which supports arm64, but it seems the Falcon-plus does not support mysql 8.0 yet, as I was getting these [failures ](https://drive.google.com/file/d/1khmRN_NBlFyeGJAq8DaAmI2soU8U2dCd/view)in both the architecture. 
```
graph: ERROR (spawn error)
hbs: ERROR (spawn error)
judge: started
transfer: started
nodata: ERROR (spawn error)
aggregator: ERROR (spawn error)
agent: started
gateway: started
api: ERROR (spawn error)
alarm: ERROR (spawn error)
time="2020-10-30T13:08:06Z" level=fatal msg="db conn failed with error connect to falcon_portal: Error 1130: Host '172.17.0.1' is not allowed to connect to this MySQL server"
FAIL    github.com/open-falcon/falcon-plus/modules/api/test     0.019s
FAIL
make: *** [Makefile:100: test] Error 1

```
Is there any plan of upgrading the mysql support from 5.7 to 8?
If yes then I will be happy to provide the support for upgrading the code.

**Comment by JimmyTinsley** [comment]
Hi @odidev 

Since mysql:5.7 docker image is not available for arm64, I use mariadb:10.1.36 instead. 
![图片](https://user-images.githubusercontent.com/37508117/98494489-16de0100-2278-11eb-8b06-2db3f04d8fb2.png)


MariaDB version 10.1-10.3 corresponds to MySQL version 5.7. 
Note that there are incompatibilities and feature differences between MariaDB and MySQL indeed, check [here](https://mariadb.com/kb/en/mariadb-vs-mysql-compatibility/#incompatibilities-between-currently-supported-mariadb-versions-and-mysql). But if you are using "general" SQL statements without "fancy features" of MySQL, compatibility shouldn't be a problem when switch to MariaDB. I haven't met compatibility issue yet (for reference only).

**Comment by odidev** [comment]
Thanks for the reply,

I am able to successfully build this package for arm64 in Travis by using jimmytinsley/makegcc-golang, mariadb docker image and incorporating these [changes](https://github.com/odidev/falcon-plus/commit/d53956f8e91c293ebd588870bfa8177b622d1b58). 
Let me know if it is ok to build the package with the jimmytinsley/makegcc-golang, mariadb docker image and the mentioned changes?
If agreed, I will raise a PR by incorporating the above changes

**Comment by laiwei** [comment]
> Thanks for the reply,
> 
> I am able to successfully build this package for arm64 in Travis by using jimmytinsley/makegcc-golang, mariadb docker image and incorporating these [changes](https://github.com/odidev/falcon-plus/commit/d53956f8e91c293ebd588870bfa8177b622d1b58).
> Let me know if it is ok to build the package with the jimmytinsley/makegcc-golang, mariadb docker image and the mentioned changes?
> If agreed, I will raise a PR by incorporating the above changes

ok, good job👍 PR is welcome:)  @odidev
